version: '3.8'
services:
  common:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      default:
    container_name: common
    environment:
      - spring_datasource_url=jdbc:mysql://localhost:3306/common
  mysql:
    image: mariadb:10.5.13
    container_name: mysql
    volumes:
      - common-data:/var/lib/mysql
    networks:
      default:
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=common
      - MYSQL_USER=mysql

volumes:
  common-data: {}

networks:
  default:
